name: dmdata_telegram_json
description: DM-DATA Telegram Json Parser
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  pedantic_mono: ^1.20.0
  test: ^1.21.4

flutter:
