name: Auto Format

# ref: https://qiita.com/blendthink/items/48e6c4b2c0f016da8c72

on:
  workflow_dispatch:
  # 毎週月曜日の日本時間で午前9時に自動実行
  schedule:
    - cron: "0 0 * * 1"

env:
  # フォーマット対象のパス
  FORMAT_PATHS: "."

jobs:
  auto-format:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      # https://github.com/kuhnroyal/flutter-fvm-config-action
      - name: Fetch flutter config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      # https://github.com/subosito/flutter-action
      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}

      - name: dart version
        run: dart --version

      - name: Format
        run: dart format --fix $FORMAT_PATHS

      # 変更が発生した場合は main ブランチに向けてプルリクエストを作成
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: auto format
          title: Auto Format
          body: This was automatically generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          base: main
          branch: auto-format
          branch-suffix: short-commit-hash